### ISSUE TITLE
Remove `IERC20` inheritance in `IInterchainToken`

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#109]
https://github.com/axelarnetwork/interchain-token-service/blob/4bbb2bc09fb31863e9b958df1bd6a9f00a7c1879/contracts/interfaces/IInterchainToken.sol#L5

It's clashing with import of Openzeppelin's `ERC20`.

It has been done in https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/interfaces/IInterchainToken.sol so please publish a new release to npm soon.

**Comment by milapsheth** [comment]
Hey, we plan to release a new version soon. But in the meantime, I recommend pointing to the git commit if you're in a hurry.

**Comment by milapsheth** [comment]
The new release addressed this
