### ISSUE TITLE
Remove `IERC20Named` inheritance in `IInterchainToken`

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#182]
https://github.com/axelarnetwork/interchain-token-service/blob/0a00533f19197a285d6bddc8ec0c2e908094ebfe/contracts/interfaces/IERC20Named.sol#L5

It's clashing with import of Openzeppelin's `ERC20`.

Openzeppelin's `ERC20` has `name()`, `symbol()` and `decimals()`:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4e17c2e95821b9bff7c2b1e099b078d319142c48/contracts/token/ERC20/ERC20.sol#L58C1-L85

**Comment by SKYBITDev3** [comment]
I see many inheritances were added to `IInterchainToken` in this commit:
https://github.com/axelarnetwork/interchain-token-service/blob/6da1bf45073c630641dfda77eda106ab9312b61b/contracts/interfaces/IInterchainToken.sol

I don't use `IDistributable` either.

Should I just import @axelar-network/interchain-token-service/contracts/interfaces/IInterchainTokenStandard.sol instead?

**Comment by re1ro** [comment]
Hey @SKYBITDev3 ! 
Yes you should import `IInterchainTokenStandard` instead.
We had a major renaming in the codebase and renamed StandardToken into InterchainToken.
