### ISSUE TITLE
Use type(T).max to get maximum value of uint

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#222]
Changing 

https://github.com/axelarnetwork/interchain-token-service/blob/9edc4318ac1c17231e65886eea72c0f55469d7e5/contracts/token-manager/TokenManager.sol#L25

to
```solidity
    uint256 internal constant UINT256_MAX = type(uint256).max;
```
is more readable and would save some gas.

**Comment by milapsheth** [comment]
Thanks, agreed, and fixed in the PR

**Comment by SKYBITDev3** [comment]
It should also be changed in:

https://github.com/axelarnetwork/axelar-examples/blob/1c8c8faaad46822125b1540c04c7062f268fea1a/examples/evm/its-canonical-token/CanonicalToken.sol#L16

https://github.com/axelarnetwork/axelar-examples/blob/1c8c8faaad46822125b1540c04c7062f268fea1a/examples/evm/its-custom-token/CustomToken.sol#L20
