### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#224]
After the many changes in the codebase, the documentation at https://docs.axelar.dev/dev/send-tokens/interchain-tokens is now largely out-of-date.

In particular, the code examples no longer work.

It should be updated ASAP.

**Comment by SKYBITDev3** [comment]
The documentation has been outdated for 2w now. So developers who have been following the outdated documentation would find that it doesn't work, which wouldn't be a good experience. It's better practice to publish the documentation at the same time as new code so that developers can follow guides that work.

**Comment by SKYBITDev3** [comment]
> We already have open PRs for docs

Is it this one?: https://github.com/axelarnetwork/axelar-docs/pull/600

It still has outdated content.

e.g. [sample custom token](https://remix.ethereum.org/axelarnetwork/axelar-docs/blob/main/public/samples/interchain-token-iinterchaintoken.sol).

**Comment by SKYBITDev3** [comment]
Documentation at https://docs.axelar.dev/dev/send-tokens/interchain-tokens/create-token still points to code that doesn't work.

e.g. @axelar-network/interchain-token-service/contracts/libraries/AddressBytesUtils.sol no longer exists.

**Comment by Olanetsoft** [comment]
Thank you for pointing that out. We will take a look and address the issue. Please note that we are constantly working on these updates through due processes and greatly value feedback from esteemed developers like you. For additional feedback, questions, or comments, please utilize our Support repository: [https://github.com/axelarnetwork/support](https://github.com/axelarnetwork/support). This will help us track and prioritize issues or discussions effectively, ensuring that your questions are always handled.

We're dedicated to enhancing our support efforts exponentially, providing you with the necessary resources and guidance to succeed and innovate. Your success is our utmost priority. Thank you.

**Comment by Olanetsoft** [comment]
This is now fixed. Thanks for flagging; for additional feedback, questions, or comments, please utilize our Support repository: https://github.com/axelarnetwork/support.
