### ISSUE TITLE
`InterchainToken`: can `init` be called successfully?

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#226]
Can `init` ever be called and get past the initialization check
https://github.com/axelarnetwork/interchain-token-service/blob/9edc4318ac1c17231e65886eea72c0f55469d7e5/contracts/interchain-token/InterchainToken.sol#L86-L97

if `_initialize()` is called in the constructor?:
https://github.com/axelarnetwork/interchain-token-service/blob/9edc4318ac1c17231e65886eea72c0f55469d7e5/contracts/interchain-token/InterchainToken.sol#L35-L41

**Comment by milapsheth** [comment]
`InterchainToken` is a default implementation of the [InterchainTokenStandard](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/interchain-token/InterchainTokenStandard.sol). It's meant to be used in conjuction with a [proxy](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/utils/InterchainTokenDeployer.sol#L45), (we're using a minimal proxy in our case). It's not meant to be extended by developers. Instead, they should extend `InterchainTokenStandard`.

**Comment by SKYBITDev3** [comment]
There would be developers who just want to quickly get started by copying example code and deploy to initially try Interchain Token Service. `InterchainToken` seems to be such an example contract from which to copy code, but it should not have to require a proxy to deploy.

Regardless of whether a proxy is required, in the code if `init` is called some time after `constructor`, then wouldn't there be a reversion with error `AlreadyInitialized` error? `_initialize()` is called in `constructor`, then when `init` is called `if (_isInitialized()) revert AlreadyInitialized();` executes.

**Comment by milapsheth** [comment]
We're adding examples in axelar-examples that developers can make use of for default interchain erc20 implementations. Might add it in this repo as well for convenience. `InterchainToken` is only meant for the tokens deployed through ITS (where we use a proxy pattern for cheap token deployments that share the same implementation). For this implementation, we want to prevent `init` to be called on the `implementation`'s storage, hence the check in the constructor. Whereas the proxy constructor isn't doing that, and thus `init` can be called to modify the proxy storage.

**Comment by milapsheth** [comment]
Examples can be found here: https://github.com/axelarnetwork/axelar-examples/tree/main/examples/evm
