### ISSUE TITLE
`InterchainToken`: Add `burnFrom`

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#228]
`InterchainToken` should include `burnFrom` so that the option is available by default for projects that duplicate `InterchainToken`'s code and also want higher security by enforcing approval of any burning of their issued tokens in the Interchain Token Service platform.

**Comment by milapsheth** [comment]
Similar comment as [here](https://github.com/axelarnetwork/interchain-token-service/issues/226#issuecomment-1858206956). `InterchainToken` will always be deployed as mint burn type. Developers who want to create custom tokens and use mint burn from type can inherit `InterchainTokenStandard` and add in their choice of ERC20 implementation.
