### ISSUE TITLE
Use `_msgSender()` and `_msgData()` so that meta-transactions will work correctly

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/interchain-token-service#229]
When dealing with meta-transactions the account sending and paying for execution may not be the actual sender, so `msg.sender` and `msg.data` should not be accessed in such a direct manner. Instead you should use `_msgSender()` and `_msgData()`.

Openzeppelin has [Context](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Context.sol) for this, making it possible to override it (e.g. [ERC2771Context](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/metatx/ERC2771Context.sol)) for apps that use meta-transactions.

Openzeppelin themselves replaced `msg.sender` and `msg.data` in many of their contracts in 2019: https://github.com/OpenZeppelin/openzeppelin-contracts/commit/d1158ea68c597075a5aec4a77a9c16f061beffd3

e.g. 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6ba452dea4258afe77726293435f10baf2bed265/contracts/token/ERC20/ERC20.sol#L109-L113

**Comment by milapsheth** [comment]
Thanks for the suggestion, while meta-transaction support is not in scope for the current release, we'll track this internally and see if there's demand for it, and security implications for the cross-chain use case.
